### ISSUE TITLE
Collections eager load all relationships when transformed

### ISSUE THREAD

**Issue by cerbero90** [rexlabsio/smokescreen-php#13]
When transforming collections, all relationships are eager loaded, not just the wanted ones.

@jodiedunlop investigated on this issue and found out that `loadRelations()` is called from within `serializeResource()`. This method is invoked on the first resource, and subsequent includes. It seems that this is probably not the right place to do it, as it can't determine which relations are necessary (defaults and ones triggered by includes).

https://github.com/rexlabsio/smokescreen-php/blob/master/src/Smokescreen.php#L362

**Comment by jodiedunlop** [comment]
Resolved in 2.0.0
